name: Java CI

on: [push]


jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
     # - uses: actions/setup-java@v3
     #   with:
     #     java-version: '17'
     #     distribution: 'temurin'
      - 
        name: Build
        run: mvn --batch-mode --update-snapshots verify
      -
        name: Build Image com Jib
        run: mvn compile com.google.cloud.tools:jib-maven-plugin:3.1.3:dockerBuild  -Dimage=localhost:5000/cvm/pipe_java_gih:latest
        
      
      -
        name:   push to local registry
        run: docker push localhost:5000/cvm/pipe_java_gih:latest
         
        
      #- run: mkdir staging && cp target/*.war staging
      #- uses: actions/upload-artifact@v3
      #  with:
      #    name: Package
      #    path: staging
     
          
